#theme: minima
title: Koodaripula.com
tagline: Parempaa tietoa IT-alan työmarkkinoista
url: https://www.koodaripula.com/
author:
  name: Eetu Korhonen
description: Itsenäinen tutkimusprojekti Suomen IT-työmarkkinoiden tilasta ja keinoista sen kehittämiseksi.

show_excerpts: false

header_pages:
 - survey.md
 - about.md

plugins:
 - jekyll-feed
 - jekyll-sitemap

minima:
  date_format: "%b %-d, %Y"
  social_links:
    twitter: Eeko_K
    github: eeko
    linkedin: eekoo

lang: "fi_FI"
webmaster_verifications:
  google: LGfda_S92Ga5KhAFMp7hiMJ26SPaODpCuORUb1jh8R0
