#theme: minima
title: Koodaripula.com
author:
  name: Eetu Korhonen
description: >
  Itsenäinen tutkimusprojekti Suomen IT-työmarkkinoiden tilasta ja keinoista sen kehittämiseksi.

show_excerpts: false

header_pages:
 - survey.md
 - about.md

plugins:
 - jekyll-feed

minima:
  date_format: "%b %-d, %Y"
  social_links:
    twitter: Eeko_K
    github: eeko/koodaripula.com
    linkedin: eekoo
